# -*- coding: utf-8 -*-
"""jahid-19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mOUMyMsLAsTLoBqH4M5Q4qh4WuReN_Z
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file
file_path = '/kaggle/input/dataset1/dataset_19_Online Course Enrollments.csv'
data = pd.read_csv(file_path)

# Group by 'Product' and sum the 'Revenue'
revenue_by_product = data.groupby('Product')['Revenue'].sum().reset_index()

# Create a bar chart
plt.figure(figsize=(12, 6))

# Bar chart
plt.subplot(1, 2, 1)  # 1 row, 2 columns, first plot
plt.bar(revenue_by_product['Product'], revenue_by_product['Revenue'], color='skyblue')
plt.xlabel('Product')
plt.ylabel('Total Revenue')
plt.title('Total Revenue per Product')
plt.xticks(rotation=45, ha='right')

# Pie chart
plt.subplot(1, 2, 2)  # 1 row, 2 columns, second plot
plt.pie(revenue_by_product['Revenue'], labels=revenue_by_product['Product'], autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)
plt.title('Revenue Distribution per Product')

# Show the plots
plt.tight_layout()
plt.show()